### PR TITLE
Quiz Rules

### PR DESCRIPTION
**Pull request by khushijohri2001**
Please review the code for my Mini Project -Quiz Click's Rules Page

The page includes:

A Header that includes Logo and Login Button.
Instructions for the Quiz
A Footer with all my social media and copyright

https://user-images.githubusercontent.com/65448358/160230195-e3f72010-9e88-4814-a5c6-f554327bf583.mp4

### CODE REVIEW

**Review by AshwiniSetty — APPROVED** [review]
Code Looks Clean, Great work.
Also, it will be good if you add previews in the PR for reference, else looks good to merge.

**Comment by khushijohri2001** [comment]
> Code Looks Clean, Great work. Also, it will be good if you add previews in the PR for reference, else looks good to merge.

will keep in mind for the next time!!
Thank you for letting me know

**Review by abhishek-bhatkar — APPROVED** [review]
Looks good to merge.
Just a suggestion, you can import svg files in img tag instead directly including in code.

**Comment by khushijohri2001** [comment]
> Looks good to merge. Just a suggestion, you can import svg files in img tag instead directly including in code.

Won't repeat the same for the next time. Thanks for suggesting

**Pull request merged**
